CREATE TABLE IF NOT EXISTS userauth (
    id VARCHAR PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR NOT NULL,
    mobile_number VARCHAR(20) NOT NULL UNIQUE,
    created_at VARCHAR NOT NULL DEFAULT CURRENT_TIMESTAMP
);
